// Complete seed script - ALL 83 movies with full information
const allMovies = [
    { title: 'Fight Club', description: 'An insomniac office worker and a soap salesman form an underground fight club that evolves into something far more dangerous. Their anarchic movement spirals out of control, threatening to destroy everything.', rentPrice: '39.99', genre: 'Drama', director: 'David Fincher', releaseDate: '1999', ageConsent: '18+', duration: '2h 19m', trailerId: 'SUXWAEX2jlg' },
    { title: 'Interstellar', description: 'A former NASA pilot ventures through a wormhole to find a new home for humanity as Earth faces extinction. His journey across the cosmos tests the bonds of time, space, and the love for his family.', rentPrice: '44.99', genre: 'Sci-Fi', director: 'Christopher Nolan', releaseDate: '2014', ageConsent: '13+', duration: '2h 49m', trailerId: 'zSWdZVtXT7E' },
    { title: 'The Sixth Sense', description: 'A child psychologist tries to help a young boy who claims to see and communicate with the dead. Their sessions reveal disturbing truths that challenge everything both of them believe.', rentPrice: '34.99', genre: 'Thriller', director: 'M. Night Shyamalan', releaseDate: '1999', ageConsent: '13+', duration: '1h 47m', trailerId: 'VG9AGf66tXM' },
    { title: 'Parasite', description: 'A poor family infiltrates a wealthy household by posing as unrelated, highly qualified workers. As the two families become intertwined, unexpected events expose the dark side of social inequality.', rentPrice: '44.99', genre: 'Drama', director: 'Bong Joon-ho', releaseDate: '2019', ageConsent: '16+', duration: '2h 12m', trailerId: '5xH0HfJHsaY' },
    { title: 'Corpse Bride', description: 'A shy groom accidentally marries a mysterious woman from the land of the dead. Torn between two worlds, he must choose between his arranged bride and his ghostly wife.', rentPrice: '29.99', genre: 'Horror', director: 'Tim Burton', releaseDate: '2005', ageConsent: '7+', duration: '1h 17m', trailerId: 'gvxBRVntShY' },
    { title: 'Coraline', description: 'A curious girl discovers a secret door in her new home leading to an idealized parallel world. But this other world hides sinister secrets and a mother who wants to keep her forever.', rentPrice: '34.99', genre: 'Horror', director: 'Henry Selick', releaseDate: '2009', ageConsent: '7+', duration: '1h 40m', trailerId: 'm9bOpeuvNwY' },
    { title: 'Fantastic Mr. Fox', description: 'A clever fox promises his wife to stop stealing, but cannot resist one last heist against three dangerous farmers. His actions put his entire community in danger.', rentPrice: '29.99', genre: 'Comedy', director: 'Wes Anderson', releaseDate: '2009', ageConsent: '7+', duration: '1h 27m', trailerId: 'n2igjYFojUo' },
    { title: 'The Shawshank Redemption', description: 'A banker wrongly convicted of murder forms an unlikely friendship in prison. Over decades, he maintains hope and works on a secret plan that will define the meaning of freedom.', rentPrice: '34.99', genre: 'Drama', director: 'Frank Darabont', releaseDate: '1994', ageConsent: '16+', duration: '2h 22m', trailerId: '6hB3S9bIaco' },
    { title: 'The Dark Knight', description: 'Batman faces his greatest challenge when a criminal mastermind called the Joker unleashes chaos on Gotham. The Dark Knight must confront his own limits to save the city.', rentPrice: '44.99', genre: 'Action', director: 'Christopher Nolan', releaseDate: '2008', ageConsent: '13+', duration: '2h 32m', trailerId: 'EXeTwQWrcwY' },
    { title: 'Pulp Fiction', description: 'The lives of two hitmen, a boxer, and a gangsters wife intertwine in four tales of violence and redemption. A groundbreaking crime saga told in non-linear fashion.', rentPrice: '39.99', genre: 'Drama', director: 'Quentin Tarantino', releaseDate: '1994', ageConsent: '18+', duration: '2h 34m', trailerId: 's7EdQ4FqbhY' },
    { title: 'Forrest Gump', description: 'A simple man with a kind heart unwittingly influences several major historical events in America. His extraordinary journey proves that life is indeed like a box of chocolates.', rentPrice: '34.99', genre: 'Drama', director: 'Robert Zemeckis', releaseDate: '1994', ageConsent: '13+', duration: '2h 22m', trailerId: 'bLvqoHBptjg' },
    { title: 'Inception', description: 'A skilled thief who steals secrets from dreams is offered a chance at redemption. He must perform the impossible task of planting an idea in someones mind through layered dreams.', rentPrice: '44.99', genre: 'Sci-Fi', director: 'Christopher Nolan', releaseDate: '2010', ageConsent: '13+', duration: '2h 28m', trailerId: 'YoHD9XEInc0' },
    { title: 'The Matrix', description: 'A computer hacker discovers that reality is a simulation created by machines to enslave humanity. He must choose to embrace his role as The One and fight for human freedom.', rentPrice: '39.99', genre: 'Sci-Fi', director: 'Wachowski Sisters', releaseDate: '1999', ageConsent: '16+', duration: '2h 16m', trailerId: 'vKQi3bBA1y8' },
    { title: 'Gladiator', description: 'A Roman general is betrayed by the emperors corrupt son and reduced to slavery. He rises through the gladiator ranks to seek vengeance against those who destroyed his family.', rentPrice: '39.99', genre: 'Action', director: 'Ridley Scott', releaseDate: '2000', ageConsent: '16+', duration: '2h 35m', trailerId: 'owK1qxDselE' },
    { title: 'Se7en', description: 'Two detectives hunt a serial killer who justifies his crimes using the seven deadly sins. Each new victim brings them closer to an unforgettable confrontation with true evil.', rentPrice: '34.99', genre: 'Thriller', director: 'David Fincher', releaseDate: '1995', ageConsent: '18+', duration: '2h 7m', trailerId: 'znmZoVkCjpI' },
    { title: 'The Silence of the Lambs', description: 'An FBI trainee must seek the help of an imprisoned cannibal to catch another serial killer. Her dangerous game of wits with Hannibal Lecter reveals more than she bargained for.', rentPrice: '34.99', genre: 'Thriller', director: 'Jonathan Demme', releaseDate: '1991', ageConsent: '18+', duration: '1h 58m', trailerId: 'W6Mm8Sbe__o' },
    { title: 'Whiplash', description: 'A young jazz drummer enrolls at a music conservatory where an instructor will stop at nothing to realize a students potential. The pursuit of perfection comes at a devastating cost.', rentPrice: '39.99', genre: 'Drama', director: 'Damien Chazelle', releaseDate: '2014', ageConsent: '16+', duration: '1h 46m', trailerId: '7d_jQycdQGo' },
    { title: 'The Green Mile', description: 'Death Row guards discover one of their inmates possesses a mysterious supernatural gift. This gentle giants presence forces them to examine their own lives and beliefs about justice.', rentPrice: '34.99', genre: 'Drama', director: 'Frank Darabont', releaseDate: '1999', ageConsent: '16+', duration: '3h 9m', trailerId: 'Ki4haFrqSrw' },
    { title: 'Joker', description: 'A failed comedian struggling with mental illness descends into madness in 1980s Gotham City. His transformation into a criminal mastermind shakes the city to its core.', rentPrice: '44.99', genre: 'Drama', director: 'Todd Phillips', releaseDate: '2019', ageConsent: '18+', duration: '2h 2m', trailerId: 'zAGVQLHvwOY' },
    { title: 'Avengers: Infinity War', description: 'Earths mightiest heroes must unite to stop Thanos from collecting all six Infinity Stones. The fate of the universe hangs in the balance in this epic confrontation.', rentPrice: '44.99', genre: 'Action', director: 'Russo Brothers', releaseDate: '2018', ageConsent: '13+', duration: '2h 29m', trailerId: '6ZfuNTqbHE8' },
    { title: 'Saving Private Ryan', description: 'Following the D-Day invasion, a squad of soldiers embarks on a dangerous mission to find and bring home a paratrooper whose brothers have all been killed in action.', rentPrice: '34.99', genre: 'Action', director: 'Steven Spielberg', releaseDate: '1998', ageConsent: '16+', duration: '2h 49m', trailerId: 'RYID71hYHzg' },
    { title: 'The Departed', description: 'An undercover cop and a mole in the police force race to identify each other while infiltrating the Irish mafia. Trust becomes impossible as paranoia consumes both sides.', rentPrice: '39.99', genre: 'Thriller', director: 'Martin Scorsese', releaseDate: '2006', ageConsent: '18+', duration: '2h 31m', trailerId: 'iQpb1LoeVUc' },
    { title: 'Titanic', description: 'A young society woman falls for a penniless artist aboard the ill-fated R.M.S. Titanic. Their forbidden romance unfolds against the backdrop of the ships tragic maiden voyage.', rentPrice: '34.99', genre: 'Romance', director: 'James Cameron', releaseDate: '1997', ageConsent: '13+', duration: '3h 14m', trailerId: '2e-eXJ6HgkQ' },
    { title: 'The Prestige', description: 'Two rival magicians in Victorian London engage in an escalating battle to create the ultimate illusion. Their obsession leads them down dark paths with devastating consequences.', rentPrice: '39.99', genre: 'Thriller', director: 'Christopher Nolan', releaseDate: '2006', ageConsent: '13+', duration: '2h 10m', trailerId: 'o4gHCmTQDVI' },
    { title: 'Django Unchained', description: 'A freed slave teams up with a German bounty hunter to rescue his wife from a brutal Mississippi plantation owner. Their journey through the antebellum South is both violent and liberating.', rentPrice: '39.99', genre: 'Drama', director: 'Quentin Tarantino', releaseDate: '2012', ageConsent: '18+', duration: '2h 45m', trailerId: '0fUCuvNlOCg' },
    { title: 'The Wolf of Wall Street', description: 'A stockbroker rises to incredible wealth through corruption and fraud on Wall Street. His excessive lifestyle of drugs, money, and power leads to an inevitable downfall.', rentPrice: '39.99', genre: 'Comedy', director: 'Martin Scorsese', releaseDate: '2013', ageConsent: '18+', duration: '3h', trailerId: 'iszwuX1AK6A' },
    { title: 'Shutter Island', description: 'Two U.S. Marshals investigate the disappearance of a patient from a remote asylum for the criminally insane. Nothing on the island is what it seems as disturbing secrets emerge.', rentPrice: '39.99', genre: 'Thriller', director: 'Martin Scorsese', releaseDate: '2010', ageConsent: '16+', duration: '2h 18m', trailerId: '5iaYLCiq5RM' },
    { title: 'Blade Runner 2049', description: 'A young blade runner uncovers a long-buried secret that has the potential to plunge civilization into chaos. His discovery leads him to find a missing former blade runner.', rentPrice: '44.99', genre: 'Sci-Fi', director: 'Denis Villeneuve', releaseDate: '2017', ageConsent: '16+', duration: '2h 44m', trailerId: 'gCcx85zbxz4' },
    { title: 'Alien', description: 'The crew of a commercial spacecraft awakens to investigate a mysterious signal and encounters a deadly life form. No one can hear you scream in space as terror unfolds.', rentPrice: '29.99', genre: 'Horror', director: 'Ridley Scott', releaseDate: '1979', ageConsent: '16+', duration: '1h 57m', trailerId: 'LjLamj-b0I8' },
    { title: 'Back to the Future', description: 'A teenager is accidentally sent back to 1955 in a time-traveling DeLorean invented by his eccentric friend. He must ensure his parents meet or risk erasing his own existence.', rentPrice: '29.99', genre: 'Adventure', director: 'Robert Zemeckis', releaseDate: '1985', ageConsent: '7+', duration: '1h 56m', trailerId: 'qvsgGtivCgs' },
    { title: 'The Godfather', description: 'The patriarch of an organized crime dynasty transfers control to his reluctant youngest son. A saga of family loyalty, power, and betrayal that spans generations.', rentPrice: '34.99', genre: 'Drama', director: 'Francis Ford Coppola', releaseDate: '1972', ageConsent: '16+', duration: '2h 55m', trailerId: 'sY1S34973zA' },
    { title: 'The Lord of the Rings', description: 'The final battle for Middle-earth begins as Frodo and Sam approach Mount Doom. Aragorn leads the forces of men against Saurons army in an epic conclusion to the trilogy.', rentPrice: '44.99', genre: 'Adventure', director: 'Peter Jackson', releaseDate: '2003', ageConsent: '13+', duration: '3h 21m', trailerId: 'r5X-hFf6Bwo' },
    { title: 'Schindlers List', description: 'A German businessman becomes an unlikely hero when he saves over a thousand Jewish refugees during the Holocaust. His factory becomes a haven from Nazi persecution.', rentPrice: '34.99', genre: 'History', director: 'Steven Spielberg', releaseDate: '1993', ageConsent: '16+', duration: '3h 15m', trailerId: 'mxphAlJID9U' },
    { title: 'The Godfather Part II', description: 'The saga continues as Michael Corleone expands his crime empire while flashbacks reveal his fathers rise to power. A tale of two generations bound by blood and ambition.', rentPrice: '34.99', genre: 'Drama', director: 'Francis Ford Coppola', releaseDate: '1974', ageConsent: '16+', duration: '3h 22m', trailerId: '9O1Iy9od7-A' },
    { title: '12 Angry Men', description: 'A jury must decide the fate of a young man accused of murder. One jurors doubts force the others to reconsider the evidence in this gripping courtroom drama.', rentPrice: '29.99', genre: 'Drama', director: 'Sidney Lumet', releaseDate: '1957', ageConsent: '13+', duration: '1h 36m', trailerId: 'A7CBKT0PWFA' },
    { title: 'One Flew Over the Cuckoos Nest', description: 'A criminal fakes insanity to serve time in a mental institution instead of prison. He inspires fellow patients to rebel against the oppressive head nurses authority.', rentPrice: '29.99', genre: 'Drama', director: 'Milos Forman', releaseDate: '1975', ageConsent: '16+', duration: '2h 13m', trailerId: '2WSyJgydTsA' },
    { title: 'Goodfellas', description: 'A young man grows up in the mob and works his way through the ranks. His rise and fall in the Italian-American crime syndicate spans three turbulent decades.', rentPrice: '34.99', genre: 'Drama', director: 'Martin Scorsese', releaseDate: '1990', ageConsent: '18+', duration: '2h 26m', trailerId: '2ilzidi_J8Q' },
    { title: 'The Usual Suspects', description: 'A sole survivor recounts the twisted events leading up to a horrific crime. His tale reveals the legendary criminal mastermind known only as Keyser Soze.', rentPrice: '34.99', genre: 'Thriller', director: 'Bryan Singer', releaseDate: '1995', ageConsent: '18+', duration: '1h 46m', trailerId: 'x3Kq3jXA8r4' },
    { title: 'Leon: The Professional', description: 'A professional hitman reluctantly takes in a young girl after her family is murdered. He teaches her his trade while she brings unexpected warmth to his solitary life.', rentPrice: '34.99', genre: 'Action', director: 'Luc Besson', releaseDate: '1994', ageConsent: '18+', duration: '1h 50m', trailerId: 'DcsirofJrlM' },
    { title: 'American History X', description: 'A former neo-Nazi skinhead tries to prevent his younger brother from following the same violent path. His prison experience has transformed his worldview completely.', rentPrice: '34.99', genre: 'Drama', director: 'Tony Kaye', releaseDate: '1998', ageConsent: '18+', duration: '1h 59m', trailerId: 'XfQYHqsiN5g' },
    { title: 'City of God', description: 'Two boys growing up in a violent Rio de Janeiro slum take different paths: one becomes a photographer, the other a drug dealer. Their fates remain intertwined.', rentPrice: '34.99', genre: 'Drama', director: 'Fernando Meirelles', releaseDate: '2002', ageConsent: '18+', duration: '2h 10m', trailerId: 'dcUOO4Itgmw' },
    { title: 'The Pianist', description: 'A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto during World War II. His talent and will to live sustain him through unimaginable horrors.', rentPrice: '34.99', genre: 'History', director: 'Roman Polanski', releaseDate: '2002', ageConsent: '16+', duration: '2h 30m', trailerId: 'u_jE7-eCI7Q' },
    { title: 'Memento', description: 'A man with short-term memory loss uses notes and tattoos to hunt for his wifes murderer. The story unfolds in reverse, mirroring his fragmented perception of reality.', rentPrice: '34.99', genre: 'Thriller', director: 'Christopher Nolan', releaseDate: '2000', ageConsent: '16+', duration: '1h 53m', trailerId: '0vS0E9bBSL0' },
    { title: 'The Intouchables', description: 'A wealthy quadriplegic hires a young man from the projects as his caretaker. Their unlikely friendship transforms both of their lives in unexpected and heartwarming ways.', rentPrice: '34.99', genre: 'Comedy', director: 'Olivier Nakache', releaseDate: '2011', ageConsent: '13+', duration: '1h 52m', trailerId: '34WIbmXkewU' },
    { title: 'Spirited Away', description: 'A young girl becomes trapped in a mysterious spirit world ruled by witches and spirits. To rescue her parents, she must work in a bathhouse for supernatural beings.', rentPrice: '39.99', genre: 'Adventure', director: 'Hayao Miyazaki', releaseDate: '2001', ageConsent: '7+', duration: '2h 5m', trailerId: 'ByXuk9QqQkk' },
    { title: 'Casablanca', description: 'An American nightclub owner in wartime Morocco must choose between love and virtue. His former lover appears with her husband, a resistance leader who needs his help.', rentPrice: '29.99', genre: 'Romance', director: 'Michael Curtiz', releaseDate: '1942', ageConsent: '13+', duration: '1h 42m', trailerId: 'BkL9l7qovsE' },
    { title: 'Modern Times', description: 'The iconic Tramp struggles to survive in modern industrialized society. His adventures in factories and on the streets offer a timeless commentary on humanity and progress.', rentPrice: '24.99', genre: 'Comedy', director: 'Charlie Chaplin', releaseDate: '1936', ageConsent: '7+', duration: '1h 27m', trailerId: 'GLeDdzGUTq0' },
    { title: 'Rear Window', description: 'A photographer with a broken leg passes time by watching his neighbors from his apartment window. He becomes convinced he has witnessed a murder across the courtyard.', rentPrice: '29.99', genre: 'Thriller', director: 'Alfred Hitchcock', releaseDate: '1954', ageConsent: '13+', duration: '1h 52m', trailerId: 'mT4a3vPFD5g' },
    { title: 'The Lion King', description: 'A young lion prince flees his kingdom after the murder of his father. Years later, he must return to take his rightful place and confront his villainous uncle.', rentPrice: '29.99', genre: 'Adventure', director: 'Roger Allers', releaseDate: '1994', ageConsent: '7+', duration: '1h 28m', trailerId: '4sj1MT05lAA' },
    { title: 'Apocalypse Now', description: 'A US Army captain is sent on a dangerous mission into Cambodia to assassinate a renegade colonel. His journey upriver becomes a descent into the heart of darkness.', rentPrice: '29.99', genre: 'Drama', director: 'Francis Ford Coppola', releaseDate: '1979', ageConsent: '18+', duration: '2h 27m', trailerId: 'FTjG-c2n3c4' },
    { title: 'Aliens', description: 'Ripley returns to the planet where her crew encountered the deadly alien, this time with a unit of colonial marines. They discover a colony overrun by the creatures.', rentPrice: '29.99', genre: 'Action', director: 'James Cameron', releaseDate: '1986', ageConsent: '16+', duration: '2h 17m', trailerId: 'oSeQQlaCZgU' },
    { title: 'The Lives of Others', description: 'A Stasi agent in East Germany becomes obsessed with a playwright and his lover. As he monitors their lives, his own worldview begins to shift dramatically.', rentPrice: '34.99', genre: 'Drama', director: 'Florian Henckel von Donnersmarck', releaseDate: '2006', ageConsent: '16+', duration: '2h 17m', trailerId: 'n3_iLOp6IhM' },
    { title: 'Grave of the Fireflies', description: 'A young boy and his little sister struggle to survive in Japan during the final months of World War II. Their story is a devastating portrait of innocence lost.', rentPrice: '29.99', genre: 'Drama', director: 'Isao Takahata', releaseDate: '1988', ageConsent: '13+', duration: '1h 29m', trailerId: '4vPeTSRd580' },
    { title: 'Paths of Glory', description: 'A commanding officer defends three soldiers on trial for cowardice during World War I. His fight against military injustice exposes the corruption of the system.', rentPrice: '29.99', genre: 'Drama', director: 'Stanley Kubrick', releaseDate: '1957', ageConsent: '13+', duration: '1h 28m', trailerId: 'nmDA02AjuhE' },
    { title: 'WALL-E', description: 'A lonely robot left on a deserted Earth discovers a new purpose when a sleek probe arrives. His journey to space and love transforms the future of humanity.', rentPrice: '29.99', genre: 'Adventure', director: 'Andrew Stanton', releaseDate: '2008', ageConsent: '7+', duration: '1h 38m', trailerId: 'alIq_wG9FNk' },
    { title: 'The Shining', description: 'A family heads to an isolated hotel for the winter where an evil presence slowly drives the father insane. The hotels dark history threatens to destroy them all.', rentPrice: '34.99', genre: 'Horror', director: 'Stanley Kubrick', releaseDate: '1980', ageConsent: '18+', duration: '2h 26m', trailerId: '5Cb3ik6zP2I' },
    { title: 'Psycho', description: 'A secretary on the run with stolen money checks into a remote motel run by a disturbed man and his domineering mother. Her stay takes a terrifying turn.', rentPrice: '29.99', genre: 'Horror', director: 'Alfred Hitchcock', releaseDate: '1960', ageConsent: '16+', duration: '1h 49m', trailerId: 'Wz719b9QUqY' },
    { title: 'Terminator 2: Judgment Day', description: 'A reprogrammed Terminator is sent back in time to protect the future leader of humanity from a more advanced assassin. The fate of mankind depends on one boy.', rentPrice: '34.99', genre: 'Action', director: 'James Cameron', releaseDate: '1991', ageConsent: '16+', duration: '2h 17m', trailerId: 'CRRlbK5w8AE' },
    { title: 'Sunset Boulevard', description: 'A struggling screenwriter becomes entangled with a faded silent film star determined to make her return to the screen. Their dangerous relationship leads to tragedy.', rentPrice: '24.99', genre: 'Drama', director: 'Billy Wilder', releaseDate: '1950', ageConsent: '13+', duration: '1h 50m', trailerId: 'ooXpSrBGpzU' },
    { title: 'Dr. Strangelove', description: 'A paranoid general orders a nuclear attack on the Soviet Union, and the President must scramble to prevent armageddon. A dark comedy about the absurdity of war.', rentPrice: '29.99', genre: 'Comedy', director: 'Stanley Kubrick', releaseDate: '1964', ageConsent: '13+', duration: '1h 35m', trailerId: '1gXY3kuDvSU' },
    { title: 'Oldboy', description: 'A man is inexplicably imprisoned for 15 years, then suddenly released. His hunt for answers leads him down a twisted path of revenge with shocking revelations.', rentPrice: '34.99', genre: 'Thriller', director: 'Park Chan-wook', releaseDate: '2003', ageConsent: '18+', duration: '2h', trailerId: '2HkjrJ6IK5E' },
    { title: 'The Great Dictator', description: 'A Jewish barber is mistaken for a ruthless dictator and must play along. Charlie Chaplins first sound film is a biting satire of fascism and intolerance.', rentPrice: '24.99', genre: 'Comedy', director: 'Charlie Chaplin', releaseDate: '1940', ageConsent: '7+', duration: '2h 5m', trailerId: 'doRE3aF1L2k' },
    { title: 'Cinema Paradiso', description: 'A famous filmmaker recalls his childhood in Sicily and his friendship with the projectionist at the local cinema. A nostalgic celebration of the magic of movies.', rentPrice: '29.99', genre: 'Drama', director: 'Giuseppe Tornatore', releaseDate: '1988', ageConsent: '13+', duration: '2h 35m', trailerId: 'hIacbbpBmXs' },
    { title: 'Harakiri', description: 'An elder ronin arrives at a feudal lords home requesting permission to commit ritual suicide. His true purpose exposes the corruption of the samurai code of honor.', rentPrice: '29.99', genre: 'Drama', director: 'Masaki Kobayashi', releaseDate: '1962', ageConsent: '16+', duration: '2h 13m', trailerId: '4cDvWjNwjRQ' },
    { title: 'Once Upon a Time in the West', description: 'A mysterious harmonica-playing stranger joins forces with a bandit to protect a widow from a ruthless assassin. An epic tale of revenge set in the American frontier.', rentPrice: '29.99', genre: 'Adventure', director: 'Sergio Leone', releaseDate: '1968', ageConsent: '16+', duration: '2h 45m', trailerId: 'MNGQ1hUyx-k' },
    { title: 'Toy Story', description: 'A cowboy doll feels threatened when a new spaceman toy becomes his owners favorite. Their rivalry turns to friendship as they face being lost together.', rentPrice: '29.99', genre: 'Comedy', director: 'John Lasseter', releaseDate: '1995', ageConsent: '7+', duration: '1h 21m', trailerId: 'v-PjgYDrg70' },
    { title: 'Your Name', description: 'Two teenagers discover they are mysteriously swapping bodies across time and space. Their connection deepens as they try to meet and prevent a looming disaster.', rentPrice: '39.99', genre: 'Romance', director: 'Makoto Shinkai', releaseDate: '2016', ageConsent: '7+', duration: '1h 46m', trailerId: 'xU47nhruN-Q' },
    { title: 'American Beauty', description: 'A suburban father has a midlife crisis after becoming infatuated with his daughters friend. His journey of self-discovery upends his entire familys carefully constructed lives.', rentPrice: '34.99', genre: 'Drama', director: 'Sam Mendes', releaseDate: '1999', ageConsent: '18+', duration: '2h 2m', trailerId: 'Ly7rq34F_0I' },
    { title: 'Braveheart', description: 'Scottish warrior William Wallace leads his countrymen in a rebellion against tyrannical English rule. His fight for freedom becomes a legend that inspires a nation.', rentPrice: '34.99', genre: 'Action', director: 'Mel Gibson', releaseDate: '1995', ageConsent: '16+', duration: '2h 58m', trailerId: '1NJO0jxBtMo' },
    { title: 'Reservoir Dogs', description: 'A diamond heist goes horribly wrong, and the surviving criminals begin to suspect one of them is a police informant. Paranoia and violence escalate in a warehouse.', rentPrice: '34.99', genre: 'Thriller', director: 'Quentin Tarantino', releaseDate: '1992', ageConsent: '18+', duration: '1h 39m', trailerId: 'vayksn4Y93A' },
    { title: 'Good Will Hunting', description: 'A janitor at MIT proves to be a mathematical genius but struggles with his troubled past. A therapist helps him confront his demons and find his true potential.', rentPrice: '34.99', genre: 'Drama', director: 'Gus Van Sant', releaseDate: '1997', ageConsent: '16+', duration: '2h 6m', trailerId: 'PaZVjZEFkRs' },
    { title: 'Requiem for a Dream', description: 'Four people chase their American dreams through drug-fueled ambitions. Their paths spiral into addiction and desperation in this intense psychological drama.', rentPrice: '34.99', genre: 'Drama', director: 'Darren Aronofsky', releaseDate: '2000', ageConsent: '18+', duration: '1h 42m', trailerId: 'lgo3Hb5vWLE' },
    { title: '2001: A Space Odyssey', description: 'A voyage to Jupiter with the sentient computer HAL turns deadly when the machine begins to malfunction. A visionary epic exploring humanitys place in the cosmos.', rentPrice: '29.99', genre: 'Sci-Fi', director: 'Stanley Kubrick', releaseDate: '1968', ageConsent: '13+', duration: '2h 29m', trailerId: 'oR_e9y-bka0' },
    { title: 'Vertigo', description: 'A retired detective with a fear of heights is hired to follow a mysterious woman. His obsession with her leads him into a web of deception and psychological torment.', rentPrice: '29.99', genre: 'Thriller', director: 'Alfred Hitchcock', releaseDate: '1958', ageConsent: '13+', duration: '2h 8m', trailerId: 'Z5jMwBFGkFU' },
    { title: 'M', description: 'A city gripped by fear hunts for a child murderer as both police and criminals close in on him. A landmark film that pioneered the psychological thriller genre.', rentPrice: '24.99', genre: 'Thriller', director: 'Fritz Lang', releaseDate: '1931', ageConsent: '16+', duration: '1h 57m', trailerId: 'IfG03Sl9dP0' },
    { title: 'Das Boot', description: 'The claustrophobic world of a World War II German submarine crew is brought to life. Their harrowing missions test the limits of human endurance and courage.', rentPrice: '29.99', genre: 'Drama', director: 'Wolfgang Petersen', releaseDate: '1981', ageConsent: '16+', duration: '2h 29m', trailerId: 'i_fg2KPHB7E' },
    { title: 'Toy Story 3', description: 'The toys are mistakenly delivered to a daycare center instead of the attic. They must escape before their owner leaves for college and theyre lost forever.', rentPrice: '29.99', genre: 'Comedy', director: 'Lee Unkrich', releaseDate: '2010', ageConsent: '7+', duration: '1h 43m', trailerId: 'JcpWXaA2qeg' },
    { title: 'The Hunt', description: 'A kindergarten teachers life is destroyed when he is wrongly accused of child abuse in a small Danish community. His struggle to prove his innocence tears the town apart.', rentPrice: '34.99', genre: 'Drama', director: 'Thomas Vinterberg', releaseDate: '2012', ageConsent: '18+', duration: '1h 55m', trailerId: 'iYKFbp_1puQ' },
    { title: 'Snatch', description: 'Unscrupulous boxing promoters, violent gangsters, and a priceless diamond come together in London. Multiple storylines collide in this darkly comic crime caper.', rentPrice: '34.99', genre: 'Comedy', director: 'Guy Ritchie', releaseDate: '2000', ageConsent: '18+', duration: '1h 44m', trailerId: 'ni4tEtuTccc' },
    { title: 'Eternal Sunshine of the Spotless Mind', description: 'A couple undergoes a procedure to erase each other from their memories after a painful breakup. But as the memories fade, they realize what theyre losing.', rentPrice: '34.99', genre: 'Romance', director: 'Michel Gondry', releaseDate: '2004', ageConsent: '16+', duration: '1h 48m', trailerId: '07-QBnEkgXU' },
    { title: 'Inglourious Basterds', description: 'A group of Jewish-American soldiers spreads fear through Nazi-occupied France with brutal tactics. Their mission converges with a theater owners plot for revenge.', rentPrice: '39.99', genre: 'Drama', director: 'Quentin Tarantino', releaseDate: '2009', ageConsent: '18+', duration: '2h 33m', trailerId: 'KnrRy6kSFF0' },
    { title: 'Full Metal Jacket', description: 'A pragmatic Marine follows his squad from boot camp through the Vietnam War. The brutal training and horrors of combat reveal the dehumanizing nature of war.', rentPrice: '29.99', genre: 'Drama', director: 'Stanley Kubrick', releaseDate: '1987', ageConsent: '18+', duration: '1h 56m', trailerId: 'n2i917l5RFc' },
    { title: 'Green Book', description: 'A working-class Italian-American bouncer becomes the driver for an African-American pianist on a tour through the segregated Deep South. An unlikely friendship develops.', rentPrice: '39.99', genre: 'Drama', director: 'Peter Farrelly', releaseDate: '2018', ageConsent: '13+', duration: '2h 10m', trailerId: 'QkZxoko_HC0' }
];

async function clearAndSeed() {
    console.log('=== CLEARING OLD MOVIES ===');

    // First, get all existing movies and delete them
    try {
        const response = await fetch('http://localhost:8080/api/movies');
        const existing = await response.json();

        for (const movie of existing) {
            await fetch(`http://localhost:8080/api/movies/${movie.id}`, { method: 'DELETE' });
            console.log(`Deleted: ${movie.title} (ID: ${movie.id})`);
        }
    } catch (e) {
        console.log('No existing movies to delete');
    }

    console.log('\n=== ADDING ALL 83 MOVIES ===\n');

    let count = 0;
    for (const movie of allMovies) {
        try {
            const response = await fetch('http://localhost:8080/api/movies', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(movie)
            });
            const result = await response.json();
            count++;
            console.log(`✓ [${count}] Added: ${result.title}`);
        } catch (error) {
            console.error(`✗ Failed to add: ${movie.title}`, error.message);
        }
    }

    console.log(`\n=== COMPLETE: ${count} movies added! ===`);
}

clearAndSeed();
